### PR TITLE
WIP Feature/updatetinyobj (not yet for merge)

### PR DESCRIPTION
**Pull request by jefferis**
more work required to adapt to API changes

### CODE REVIEW

**Comment by trevorld** [comment]
> @trevorld can I include your pawn.obj file as another test? Are there any license implications?

Sure, I'm happy to give you permission to use it.  I wrote from scratch the R code that generated that OBJ code/texture so no license implications.  Pretty sure under American law the computer-generated ``pawn.obj`` is not sufficiently original/creative to be copyrightable, for international jurisdictions with more restrictive copyright schemes I'm happy to let you use it under [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) terms.

**Comment by jefferis** [comment]
@trevorld I'm really sorry that this was not merged. I have just sent an invitation for this repo. If you have the bandwidth to complete the merge, I would be very happy for you to do so; I would then handle CRAN.

**Comment by trevorld** [comment]
* Okay, I can complete the merge.  Is the following is okay?:

  * Double check that R CMD check still passes with latest {rgl} release
  * Bump version number to v0.4.0
  * Do a basic "squash" merge for a cleaner commit history

**Comment by jefferis** [comment]
Thank you @trevorld. I know it's a long series, but I would be inclined not to squash just for the record. however if you would like to squash your commits, you are welcome.

**Comment by trevorld** [comment]
* The pawn from #6 renders correctly
* OBJ texture rendering worked beautifully with a test using https://github.com/piecepackr/piecepackr/pull/249
* I've updated to a new **development** version number
* R CMD check returns the following two NOTES:

```
❯ checking installed package size ... NOTE
    installed size is  5.7Mb
    sub-directories of 1Mb or more:
      libs   5.5Mb

❯ checking pragmas in C/C++ headers and code ... NOTE
  File which contains pragma(s) suppressing diagnostics:
    ‘src/tiny_obj_loader.h’
```

A quick Google check suggests the first NOTE is very common in `{Rcpp}` packages on CRAN.  I have no idea whether the second NOTE is serious or not.

**Comment by jefferis** [comment]
Great!

As you say the first note is common and is of no concern. I'm afraid the second note will need an explanation and it's not guaranteed that CRAN will accept. 

See https://github.com/xtensor-stack/Xtensor.R/issues/11 for an example. I think this means at a minimum that we need to figure out what compiler a warning is being suppressed by turning off the #pragma.

**Pull request closed without merging**
