### PR TITLE
fix: Preserve texture coordinates in 'tinyshape2mesh3d()'

### PR DESCRIPTION
**Pull request by trevorld**
* This seems to work pretty well for some obj files of mine that ``rgl::readOBJ`` can't read (e.g. throws "triangulation" error) that use "u v" texture coordinates, don't know if this works for files that use "u v w" style texture coordinates (which ``rgl::readOBJ`` doesn't support)
* User needs to manually set texture file information in ``rgl`` i.e. ``shade3d(read.obj("file.obj", convert.rgl=TRUE), material=list(texture="file.png"))``

### CODE REVIEW

**Comment by jefferis** [comment]
thanks so much for the PR @trevorld! Would it be possible to add a small test with an example test mesh with texture data to https://github.com/jefferis/readobj/blob/master/tests/testthat/test-loadobj.R?

**Comment by trevorld** [comment]
Okay, I'll a small test.

**Comment by jefferis** [comment]
Thanks @trevorld! Could you have a lighter suggests than magick? There is a basic png reader iirc. Or do you need to do some manipulation that I didn’t notice yet?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by trevorld** [comment]
I've removed the visual tests.  If ``expect_equal(tilesl, tilesl_baseline)`` is ``TRUE`` and you know that the basilne version's texture render worked then I guess there is no real need to do a visual test since the mesh objects are the same.  I've put in test comments some code that allows for quick manual visual examination that the texture render works in rgl in case you make some non-reverse-compatible changes in ``readobj`` structures in the future.

**Comment by jefferis** [comment]
Thanks again for the PR!

**Pull request merged**
